### PR TITLE
Improved isHostnameAllowed(String url)

### PR DESCRIPTION
**Pull request by rignaneseleo**
I think that check the end of the domine is better and more efficient :)

### CODE REVIEW

**Comment by mwaclawek** [comment]
Thanks!

Currently, both `http://` and `https://` are stripped and then the library checks if the URL *starts* with the supplied hostname. That should work in most cases, but would probably not work with other protocols (which?) or when the URL has HTTP basic authentication, etc.

So replacing the string `url` with the parsed version `Uri.parse(url).getHost()` may actually be a good idea.

But why use `endsWith` instead of `startsWith` (or `equals`)?

**Comment by rignaneseleo** [comment]
Because usually you know the end of the domain. 
For example for my app (SlimSocial for Facebook), I know that urls end with Facebook.com so it opens also m.facebook.com, touch.facebook.com, 0.facebook.com .. etc solving my need :)

**Comment by mwaclawek** [comment]
Thanks! You're right, of course. Subdomains should be included as well.

But your solution would match `allaboutfacebook.com` as well.

What about this improved solution?

```java
String actualHost;
for (String expectedHost : mPermittedexpectedHosts) {
	actualHost = Uri.parse(url).getHost();

	if (actualHost.equals(expectedHost) || actualHost.endsWith("."+expectedHost)) {
		return true;
	}
}
```

**Comment by rignaneseleo** [comment]
generally could be inaccurate but in my case it's ok.

**Comment by mwaclawek** [comment]
This should have been implemented in https://github.com/delight-im/Android-AdvancedWebView/commit/da127f967f8dcf0ce5a0297c58e9bef2cc1a5ae8 now.

Can you please check if it's working? You should be able to update the dependency from `compile 'com.github.delight-im:Android-AdvancedWebView:v2.1.0'` to `compile 'com.github.delight-im:Android-AdvancedWebView:da127f967f8dcf0ce5a0297c58e9bef2cc1a5ae8'` for this.

Thank you!

**Comment by rignaneseleo** [comment]
It works but as I wrote, it is **inaccurate**.

Maybe it's better write another method. 
You can use addPermittedEndHostname() and after do:
```
actualHost = Uri.parse(url).getHost();
for (String expectedHost : mPermittedexpectedHosts) { 
    if (actualHost.equals(expectedHost)) {
        return true;
    }
}
for (String expectedEndHost : mPermittedexpectedEndHosts) { 
    if (actualHost.endsWith(expectedEndHost)) {
        return true;
    }
}
```

**Comment by mwaclawek** [comment]
Sorry, why do you think it's in accurate?

It's as accurate as it could be, because it checks if the domain is either a direct match or a subdomain of the permitted hostname. That is exactly what you were asking for, isn't it?

Doesn't it work for you?

**Comment by rignaneseleo** [comment]
If I would for example only facebook.com:  
```
addPermittedHostname("facebook.com"); so actualHost="facebook.com";
with actualHost="m.facebook.com";
actualHost.equals(expectedHost) -> false 
actualHost.endsWith(expectedHost) -> true
```

**Comment by mwaclawek** [comment]
Did you try it? With the current explanation, adding `facebook.com` as a permitted hostname should be sufficient to allow all of the following domains:

 * facebook.com
 * www.facebook.com
 * m.facebook.com
 * en-us.facebook.com
 * 0.facebook.com

That is, all subdomains and the hostname itself. That's what you want, isn't it?

**Comment by mwaclawek** [comment]
But `allfacebook.de` would not work as an actual hostname, for example.

**Comment by rignaneseleo** [comment]
I'm telling you that IN MY CASE it works. Because I need to include all subdomains. 

BUT if you want to publish it for everyone, you should implement it in a more accurate way. Because someone could want permit ONLY the main domain WITHOUT subdomains. 

I hope you understand :)

**Comment by mwaclawek** [comment]
Thanks, now it's clear :)

The new behavior is really the better way, I agree with you. But I also think it's what most people will need. So we'll leave it until somebody needs it changed again ;)

Thank you!

**Comment by rignaneseleo** [comment]
I can continue  using 'com.github.delight-im:Android-AdvancedWebView:da127f967f8dcf0ce5a0297c58e9bef2cc1a5ae8' ? or it can elapse?

**Comment by mwaclawek** [comment]
That's fine, that version should continue to be available. But whenever possible, you should use one of the stable versions that include a version number instead of the commit hash. See the example in the README.

**Pull request closed without merging**
