### PR TITLE
add multiupload

### PR DESCRIPTION
**Pull request by james2001**
Possibility of a multiple upload

### CODE REVIEW

**Comment by mwaclawek** [comment]
Thank you very much!

I will be checking this implementation and all the edge cases :)

So you have tested this and it's indeed working? The [ClipData](http://developer.android.com/reference/android/content/ClipData.html) has originally been for clipboard content, obviously, but it can also be used with file uploads?

I found a reference here: https://developer.android.com/guide/components/intents-common.html#GetFile

However, this document does only cover passing file URIs via `Intent` instances, not specifically file uploads.

Have you tested this on different API levels? I will do so, otherwise. From the docs linked above, it seems this may only work on API levels 18+.

**Comment by BernardJeremy** [comment]
Hello,

We're testing right now if our modification is available with API levels lower than 18 :)

Indeed, the ClipData can also be used with file uploads, Intent use it to save the selected files when the extra EXTRA_ALLOW_MULTIPLE is set to true (https://developer.android.com/guide/components/intents-common.html#Storage).

**Comment by ojdupuis** [comment]
Any news about this PR ?

**Comment by BernardJeremy** [comment]
Hi,
This PR implement a features using [EXTRA_ALLOW_MULTIPLE](http://developer.android.com/reference/android/content/Intent.html#EXTRA_ALLOW_MULTIPLE), which is only available since API 18. For this reason, I'm not sure the owner of the repository wants to merge this enhancement.

**Comment by mwaclawek** [comment]
@james2001 Thanks a lot for your excellent first attempt at a solution!

Support for multiple file uploads has been added in https://github.com/delight-im/Android-AdvancedWebView/commit/617999a6d9b0ef318a5ad01ab84b44e212b6a198

As we've discussed here already, though, support is possible on Android 5.0+ only.

This feature is available in the latest release now. So you just have to update your dependency, as shown in the README. Please note that you will have to take a look at the notes in `Migration.md`, however.

**Comment by james2001** [comment]
thanks

**Pull request closed without merging**
