### PR TITLE
Sdk and Java code updates

### PR DESCRIPTION
**Pull request by TacoTheDank**
I would like to separate these changes into different pull requests, but these changes are all dependent and related to each other, so the order in which they are be merged may cause conflicts. To work around this, I broke this down into 4 commits, with each commit having its own group of changed files.

## (1/4) root of project (gradles and wrapper)
- Update Android Studio 3.0.1 -> 3.3.0
- Update Dcendents plugin 1.4.1 -> 2.1
- Update Gradle 4.1 -> 4.10.3

## (2/4) library files
- buildToolsVersion 26.0.2 -> 28.0.3
- Compile and target Android Pie
- minSdkVersion 8 -> 14 (potentially breaking change; apps must now set minSdk to at least 14)
- Compile using Java 1.8 and utilise changes that come with it (potentially breaking change; apps using it must now compile with Java 1.8)
- Delete deprecated code of anything under sdk 14 as library will now support minimum of 14
- Reformat code
- Solve onUnhandledInputEvent error above sdk 23 using code suggested by @anggrayudi in https://github.com/delight-im/Android-AdvancedWebView/issues/83
- Replace ```else if```s with [```switch```](https://github.com/delight-im/Android-AdvancedWebView/commit/a9cb1efa84570abd6bef1d708258db4c002dccd9#diff-0a4445e97511f3c38ffab8481b4422d2L1144)

## (3/4) sample app files (not important; only reflects changes in library, and some other stuff)
- buildToolsVersion 26.0.2 -> 28.0.3
- Compile with Android Pie (but target 22, as I'm not good at runtime permission checks)
- Compile using Java 1.8
- Replace dependency compile with implementation
- Reformat code
- Create new launcher icons (just the default android head with grid background)
- Delete values-v11 and values-v14, make values-v14 the default (values), and add values-v21 material theme

## (4/4) README.md files to reflect these changes
- Replace http with https
- Replace ```compile 'com.github.delight-im:Android-AdvancedWebView:v3.0.0'``` with ```implementation 'com.github.delight-im:Android-AdvancedWebView:v3.1.3'```
- Replace ```"file:///sdcard/Android/data/com.my.app/my_folder/index.html"``` with ```Environment.getExternalStorageDirectory().getPath()``` [here](https://github.com/delight-im/Android-AdvancedWebView/commit/b5085b19e75d4e8052e58875988e409e61241f9e#diff-04c6e90faac2675aa89e2176d2eec7d8R369) (hopefully I did that right)

### CODE REVIEW

**Comment by badener95** [comment]
Why did you rename the hasError method to hasNoError? This might just unnecessarily break things...

**Comment by TacoTheDank** [comment]
Because it was always inverted, I figured I would un-invert it and rename it to its opposite...

**Comment by ocram** [comment]
@TacoTheDank Your contribution shows a very good understanding of application development in general and also of this library, but I’m not sure we’ll be able to merge these changes into a library that highly values stability and avoids breaking changes whenever possible.

**Comment by TacoTheDank** [comment]
@ocram Thank you :)

If you are uncomfortable with accepting such large changes, I believe it would be possible to merge this into a development branch that could be slowly integrated into the master. Is this a good idea?

**Comment by TacoTheDank** [comment]
And also, about the cleartext https problem in Android 9.0... A user was experiencing this in an app I develop. If you'd like, you can read it here: https://gitlab.com/TacoTheDank/APKMirror/issues/3

**Comment by TacoTheDank** [comment]
I'll close this for now. Maybe I'll eventually do this again, but better.

**Pull request closed without merging**
